# ==========================================
# APPLICATION
# ==========================================
spring.application.name=e-learning
server.port=8080
spring.profiles.active=local

# ==========================================
# JPA / HIBERNATE (commun)
# ==========================================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# LOGGING
# ==========================================
logging.level.org.springframework.security=DEBUG

# ==========================================
# JWT
# ==========================================
app.jwt.secret=MyVeryLongSecretKeyForLearningPathPlatformProject2026
app.jwt.expiration=86400000

# ==========================================
# SWAGGER
# ==========================================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html